# Generated by Django 4.0 on 2022-01-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='provider',
            fields=[
                ('provider_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tag_id', models.CharField(max_length=50, null=True)),
                ('license_year', models.IntegerField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('station_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=50)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
            ],
        ),
        migrations.CreateModel(
            name='pass_event',
            fields=[
                ('pass_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('charge', models.FloatField()),
                ('stationRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.station')),
                ('vehicleRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('phoneNo', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('ssn', models.IntegerField()),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.vehicle')),
            ],
        ),
    ]
